[package]
name = "fluxion"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.56", features = ["derive"] }
crossterm = "0.29.0"
ratatui = "0.30.0"
ropey = "1.6.1"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = "0.3.22"
